### ISSUE TITLE
Database fails to initialize due to missing release date

### ISSUE THREAD

**Issue by fenhl** [mbr/pymtgjson#3]
``` python
  File "./type-analysis", line 24, in card_db
    return mtgjson.CardDb(db)
  File "/usr/local/lib/python3.5/site-packages/mtgjson/__init__.py", line 143, in __init__
    key=itemgetter('releaseDate'))
KeyError: 'releaseDate'
```

It appears that if there are any sets without the `releaseDate` entry, the database will fail to initialize. This is caused by https://github.com/lsmoura/mtgjson/issues/148 which is already fixed on master, but no release has been made yet that includes the fix. So an option would be to wait until the next MTG JSON release.

**Comment by mbr** [comment]
Is this fixed now or do I need to implement a workaround here? I'd like to close the issue, either way is fine =)

**Comment by mbr** [comment]
If you could supply 3-4 lines to reproduce the error, that'd be great as well.

**Comment by fenhl** [comment]
It has been fixed by a recent release.

**Comment by fenhl** [comment]
To clarify, the error appeared by simply calling `mtgjson.CardDb.from_url()`.

**Comment by mbr** [comment]
Thanks for reporting it nonetheless! Works on my end as well.
