### ISSUE TITLE
find_card_by_name function doesn't exist?

### ISSUE THREAD

**Issue by multimeric** [mbr/pymtgjson#4]
This function is listed as a member of CardDb instances in the [documentation](https://github.com/mbr/pymtgjson/blob/master/README.rst#example-use) but the function doesn't seem to exist. I can't find it in the source code either: https://github.com/mbr/pymtgjson/blob/master/mtgjson/__init__.py#L121

Should the documentation be updated, or is this function missing?

**Comment by mbr** [comment]
Thanks for the report, docs have been fixed.

**Comment by multimeric** [comment]
Thanks, that's really helpful!
